[package]
name = "edgeman-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
chrono = { version = "0.4.31", features = ["serde"] }
k8s-openapi = { version = "0.20.0", features = ["v1_28"] }
serde = { version = "1.0.190", features = ["derive"] }
